### ISSUE TITLE
Host / run the game on a server not working?

### ISSUE THREAD

**Issue by fransyozef** [pongstylin/tactics#57]
I tried to host the game on my server, just to see if it works.

I've build the dist and the files where generated in static/ folder. These files I transfered to Zeit Now to test: https://static.thehangrycoder.now.sh/

When I start the game (for example the classic https://static.thehangrycoder.now.sh/classic.html) , I see it gets loaded, but after a while hangs.

When I check the network tab I see a 404's on some POST commands. Is there something I'm missing?

**Comment by pongstylin** [comment]
I fixed it for you.  Due to licensing constraints, I do not include the animation resources in the repository.  So, it is externally hosted.  But I am also unable to define an open-ended CORS configuration that would allow just any site to make use of the externally hosted resources.  So, I explicitly allowed access to your site.  Now, the game loads just fine.

The 404's were just a symptom.  Whenever an error occurs on the client, it posts the error to the server so that it may be logged.  But, you have not changed the default location where it posts those errors and that location doesn't exist in your instance (since you are hosting a fully static site right now).

**Comment by fransyozef** [comment]
hmm I see .. It still doesn't run btw :) .. 

But I do see the CORS indeed. For example

https://tactics.taorankings.com/sounds/sound1.mp3

Can you also try with this one: https://static-fatfk5sjc.now.sh ? The other one (https://static.thehangrycoder.now.sh/). Maybe thats why the CORS is blocking.


![Screen Shot 2019-11-20 at 18 38 27](https://user-images.githubusercontent.com/13717081/69263153-0646fd80-0bc5-11ea-9d84-2f127a7f88de.png)

**Comment by pongstylin** [comment]
I have now added "https://static-fatfk5sjc.now.sh" and verified it loads fine as well.  Bear in mind, that CORS failures may be cached.  Open developer tools in Chrome and make sure the "Disable cache" checkbox is checked to work around the issue.

**Comment by fransyozef** [comment]
Thanks .. will do check it .. I think I can also config Zeit Now to bust the cache.

**Comment by fransyozef** [comment]
nice it works

![Screen Shot 2019-11-20 at 18 45 53](https://user-images.githubusercontent.com/13717081/69263667-0b587c80-0bc6-11ea-938d-5717d9471601.png)

**Comment by fransyozef** [comment]
And what do I need to get

https://static.thehangrycoder.now.sh/createGame.html

working?

I see it tries to connect to localhost

![Screen Shot 2019-11-20 at 18 48 31](https://user-images.githubusercontent.com/13717081/69263846-67230580-0bc6-11ea-8daa-31c8058423cc.png)

Or is this not supported yet?

**Comment by pongstylin** [comment]
It requires a WebSocket endpoint (that's what "ws" stands for).  Since your site is secured, the websocket endpoint has to be secured as well (and would be "wss" instead).

It most certainly is supported.  You can see an example on my production URL.  It uses a websocket endpoint of "wss://tactics.taorankings.com/api".
https://tactics.taorankings.com

I host the game in Amazon Cloud (AWS).  I use a CloudFront distribution (CDN) that serves a static site, but internally redirects "api" to a server instance.
